export enum ProvidersEnums {
  POST_MODEL = 'POST_MODEL',
  BLOG_MODEL = 'BLOG_MODEL',
  USER_MODEL = 'USER_MODEL',
  COMMENT_MODEL = 'COMMENT_MODEL',
  LIKE_STATUS_COMMENTS = 'LIKE_STATUS_COMMENTS',
  LIKE_STATUS_POSTS = 'LIKE_STATUS_POSTS',
  LAST_10SEC = 'LAST_10SEC',
  CONFIRM_CODE = 'CONFIRM_CODE',
  BL_REFRESH_JWT = 'BL_REFRESH_JWT',
}
